### ISSUE TITLE
Create Code of Conduct

### ISSUE THREAD

**Issue by joshuavial** [enspiral/improvements#102]
Create a code of Conduct for Enspiral

History of the work done on this previously is in [this Loomio](https://www.loomio.org/d/3kebtDN4/code-of-conduct-and-conflict-resolution-documents).

**Comment by joshuavial** [comment]
@rdbartlett can you get the well working group to take over this ticket when they get setup please

**Comment by coopchange** [comment]
@joshuavial this could be labelled #wg-well-working, i think, at this point. not sure how to create label

**Comment by gcassel** [comment]
We've prepared a complete draft Personal Conduct Agreement, and intend to make a prominent network-wide "request for comments" starting around 27 March.

**Comment by gcassel** [comment]
[**Here's the Loomio discussion**](https://www.loomio.org/d/acrlk2zA/adopting-a-personal-conduct-agreement-with-conflict-resolution-guidelines) for the draft Personal Conduct Agreement.

**Comment by gcassel** [comment]
Here are our [survey results](https://docs.google.com/document/d/1nyD2wumAMdgeGXGAqkuZ5mvr3MHlFwcV1SARWcUppPM/edit#) and our collaborative [notes from yesterday's meeting](https://docs.google.com/document/d/1nyD2wumAMdgeGXGAqkuZ5mvr3MHlFwcV1SARWcUppPM/edit#).

Within the next two weeks, we expect to finish a "2.0" version of the Personal Conduct Agreement which may be practically ready for (hopefully) network adoption.   We'll try to resolve all major concerns before then.

We'll make a prominent request for comments on that 2.0 version, and offer meeting opportunities, before launching an Enspiral Loomio proposal.

**Comment by susanbasterfield** [comment]
Both have passed - john needs to create pull requests for some typos, and add reference to the other agreement.  Outcome will be posted this week, and Toni looking to create the video on the pull request process

**Comment by coopchange** [comment]
thanks for notating, @susanbasterfield (:

**Comment by gcassel** [comment]
Please note that the planned "prominent request for comments" which I referred to in my last comment here was not performed.   

Please also note that I consider the error in the Harassment and Abuse Policy to be a bit more than a typo, because the missing sentence was a key conceptual element.    Also please note that I don't consider it to be appropriate to use Github pull requests to add or subtract *any* content from Significant Decisions.

I'm  documenting these points in some detail because I consider that to be my personal responsibility.    I don't intend to argue with anyone about these subjects, or to persuade anyone to adopt my cultural or technical standards.
