### ISSUE TITLE
Cat herding really really sucks

### ISSUE THREAD

**Issue by joshuavial** [enspiral/improvements#139]
One of the most demotivating tasks in Enspiral is trying to herd all the cats to do something simple - fill in a form, submit a profile etc.

What can we do to make this easier?

**Comment by gcassel** [comment]
I'm just about the least coercive person I know, but for *really important stuff*  I might suggest that specific community privileges are made contingent upon responsible participation.   I.e.  eventually suspend someone's Slack or Loomio rights (very temporarily) if they don't fill out an important form.      

For other stuff, maybe a bit of bribery.  (Though it's certainly preferable to help people feel intrinsically socially motivated to enhance the community's resources.)

**Comment by agentlewis** [comment]
lets gamify it! set up a leader board ;) set up a badge system.

more seriously what about some sort of wall that is a live update of people who need to fill it in and everyone agrees to shoulder tap/nudge 1-2 people that have yet to do it. 

That way we distribute the herding. instead of there being one herder and many cats. we are all cat-herder herders that micro herd each other.

If I had visibility on who had yet to act I would totally remind a couple.
