### ISSUE TITLE
Launch new enspiral.com website

### ISSUE THREAD

**Issue by joshuavial** [enspiral/improvements#145]
- [ ] get website details from phil
- [ ] find team to finish off
- [ ] launch

**Comment by phillcoxon** [comment]
I've been working on this site over the last couple of weeks prepping for launch. Susan and I meeting today at 2pm to review.  Basically good to go once we update:
* venture profiles
* add proto-ventures?
* update member profiles in line with the Member shareholder update happening today.

**Comment by phillcoxon** [comment]
Phill & Susan meeting notes from 31 May. 

**Timeframe**

Aim for launch in current sprint cycle.

**Content**

- Members
    - Get all 49 Members onto the site, even if bios are empty initially. Launch and then ask Members to fill out as needed.
- Ventures
    - Update latest list of ventures from handbook
    - Request contact email address for each venture for contact page

**People Page**

- Random sorting for Members
- Change “View my Portfolio” -> "More about me"

**Network Overview**

-  Susan to ask JV to provide more timeline entries (date, description, image if available)

**Our Ventures & Teams**

- remove “Teams” from the title.

**Events Menu item**

- Enspiral Events
- Affiliated Events page
    - OuiShare etc.
- Open Source Open Society -> OSOS site

**Footer** (similar to Resilience.com)

- Twitter
- Facebook
- Map

**Videos Page**

 - videos from Enspiral.com
 - what other new videos are on the Enspiral youtube?

**Network Overview**

- change ink to diversity policy on the handbook page

**SEO**

Remap current enspiral.com urls -> new site.

**Time permitting** (or move to next sprint)

- Foundation Member/partner location
    - Member’s enter location in profile
    - Map to large Google Maps
    - Display Member locations with optional contact number
- Footer location map

**Comment by phillcoxon** [comment]
Progress Meeting on Mon 13 Jun - Susan, JV, Phill

Home Page
- [ ] Improvements link Waffle -> github
- [ ] Add contact link to footer
- [ ] Network Effects - replace with handbook
- [ ] Disable Network Effects page (may update in future sprint)
- [ ] Kill search for time being

Network Overview
- [ ] Remove values from Network Overview page (out of date)

People Page
- [ ] People page - remove caching to allow for random people display

Navigation
- [ ] Remove Network Effects, Events links
- [ ] Fix About Enspiral -> Network Overview


Contact Page
- [ ] Remove last name, phone number, subject, captcha
- [ ] Email address at the top

FAQ Page
- [ ] Fix header issues

Public Mailing List
- [ ] Create Mailchimp public Newsletter list
- [ ] Gravity Forms integrate to MailChimp
- [ ] Place sign up forms on site

People
- [ ] Ensure all current Members are included. Seek details from new Members. 

Ventures
- [ ] Reimport all ventures from handbook venture list
- [ ] Display excerpt on /ventures page linking to full bio page
- [ ] Fix code so excerpt logo jumps to full bio page, not external site.
- [ ] Add additional link to external website on venture excerpt, full bio page

Timeline 
- [ ] Find an image for 2013
- [ ] JV to provide additional timeline entries. 


Backlog Tasks

* Our Spaces page (EDA Akl, EDA Wgtn, Rabid Space)
	- [ ] Create new page
	- [ ] Link from the "About Enspiral" page to "Our Spaces" page
* FAQs moved to Handbook
* "Get Involved" page at top level nav 

Target:  complete and launch in current sprint (ending 24 June 2016)

**Comment by phillcoxon** [comment]
Ventures requiring profiles to be completed before launch:
- [ ] BuckyBox
- [ ] Enspiral Services
- [ ] Rabid 
- [ ] Scoop

**Comment by phillcoxon** [comment]
Next steps: 
- [ ] Move to Enspiral github repo
- [ ] Write up readme with dev notes for deployment to staging / production
- [ ] Access for JV to make changes
- [ ] JV / Susan to make additional minor tweaks to tighten up the site. 
- [ ] Invite Foundation Members to submit their profiles. 
- [ ] Submit for Member review / feedback

**Comment by SlimeyD** [comment]
Adding some feedback on the site. The timeline on 'our network' page is a bit finicky on both mobile and desktop. Not sure what you can do to make this smoother given it may be limitatiosn of the plugin. At the moment each clickable element of the timeline is symbolised as a '1' - seems weird. Would be nice to click at any point of the timeline or have dates outlined. Also, it would be great to update my profile and links before​ it goes live

**Comment by rdbartlett** [comment]
FYI [here's the draft text](https://docs.google.com/document/d/1Xomm_FTuY_zaYcNdAkHWoPvUoSxpAE5QbCaef7EuqTo/edit) for the Loomio update, due to go out after the site is published.

**Comment by Camcan** [comment]
##Feedback, as requested. This is what I could see on desktop
**Home Page**
 - Briefly visible loading spinner in the top left; is this supposed to be here (is blue-ish on blue)?
 - Top panel ("More people working on stuff"...) Sentence doesn't contain reference object. Suggestion: "Enspiral; more people working on stuff that matters". Also; I feel this section should stand out more from the other colored, clickable sections or perhaps be joined with "Network Overview", as that page repeats the same words as a title. 
 - "Network Overview"  background img loaded after page render for me. Too high res? 
 - General colors
 - Tweets: Can slider buttons be on either side if the tweet container, instead of on the right? Would make functionality clearer/more intuitive.

**Network Overview Page**

 - +1 for removal of numbering on "Enspiral's Evolution" points. Simple bullets more accurate?
 - Levels of Engagement Seciton; Suggestion: "Foundation Members -  [Propose] ventures, [invite] contributors, and [introduce] new members" 
 - Timeline: Zoom out; should be able to see more nodes. Need "JANUARY"? No other months shown..

**Ventures Page**

 - Align-center the filter options. 
 - Enspiral is a Venture of Enspiral? Self linking... Should be separate section of page entirely to accentuate the point that Enspiral's a product of its members; my understanding is that Enspiral isn't a company on its own.  This point is made elsewhere, anyhow. 
 - Enspiral Services should have more than a repeat of the Enspiral logo as the image; is confusing. 

**People Page**

 -  Link to people agreement could be let viewer know they're going to member handbook documentation, ie instead of 'here'. 
 >"Find out how Enspiral Contributors and Foundation Members join and relate to the network, and the expectations that come with participation in the collective [by referring to the member handbook]."
 
**Places**

- Addition of logos to spaces? 

**Get Involved** 

- Typo: "..hosts drinks on Fridays athat everyone.." 

**Contact**
- Here there should be clear routes to Physical Locations & Ventures pages.
