### ISSUE TITLE
document slack channels

### ISSUE THREAD

**Issue by joshuavial** [enspiral/improvements#242]
138 channels are a lot for people to navigate - some kind of documentation to help new folks would be useufl

**Comment by jessykate** [comment]
i just join [progcode](http://www.progcode.co/) and they have a nice integration with [airtable](https://airtable.com/shruhGsBZDvAZ2YMm/tblMQXMihxvUGxdZF) that lists all their slack channels, organized by type (not sure where _that_ data comes from), includes the channel description and whether it is active or not. it's still a bit overwhelming but was really helpful to see it all laid out. 

assuming it's custom, my personal wish list would be to include number of members and frequency of messages. 

i've not used airtables before but it looks pretty cool. i'll ask them how they made it.

**Comment by jessykate** [comment]
argh, it turns out that they are just doing this manually. 

in the process i ended up reading up on some of the slack API calls. it would be possible to make a script that documents all the channels and then for each channel does an API call to that channel's history and figures out things like number of members, most recent messages, and message frequency. 

this would be a fun mini project and IMHO useful for other communities too. i'm surprised it doesn't exist yet. but i can't commit to it right now, so i'm just going to pretend i'm forgetting about it and if i get inspired/find time i'll pull it off the board... :).

**Comment by joshuavial** [comment]
I like the idea of a mini project @jessykate 

@mischa-saunders is interested in having a look

**Comment by mischa-s** [comment]
This sounds like fun and I'm keen, but I am also doing a workload review currently and will come back to this if time allows

**Comment by coopchange** [comment]
hi @mischa-s - you interested in picking this up? @sanchemin, @lucasexpresso, and I may be keen to support this work in terms of exposing it to the network/ new Contributors

**Comment by coopchange** [comment]
ah! i didn't mean to close this :S trying to figure out how to open it again...

**Comment by coopchange** [comment]
regardless of the api-work, I'd be interested to merge this ticket with #312

**Comment by phoebetickell** [comment]
Hey @coopchange @mischa-s I'd be happy to pick this up and think I could get a script working by the end of the week. Is everyone happy for me to have a stab at this?

**Comment by coopchange** [comment]
Go for it @phoebetickell

**Comment by jessykate** [comment]
yay! would love to see how you get on @phoebetickell. this will be so useful :).

**Comment by mdshearer** [comment]
If we're able to get Slack metrics, Ops could do a bit of channel dusting. eg. no messages for 1 year = archive.

**Comment by coopchange** [comment]
Where is this going to live? Plans for signage enabling people to find it (perhaps Handbook, and/or link in onboarding emails?)

**Comment by phoebetickell** [comment]
Good question @coopchange. I am working with Anouk on some data viz. I think Handbook would be a good idea, and my other vision is for an onboarding PDF for new contributors. That might be my next #engagement mini-project after scoping out the onboarding video webinars with Joshua, and the survey avec toi.
I have two spreadsheets on data that are on #working-out-loud. I can also send direct to you @mdshearer if you want to take a look - there are lots that are totally inactive - although interesting for history!

**Comment by mdshearer** [comment]
Yes please! I would LOVE to help tidy that up and make it a little easier to navigate. Perhaps the top 30 channels could have some kind of naming convention to help (like "WG" etc).

**Comment by MattiSG** [comment]
Removing some dust here 😉 

The issue of lack of readability & maintenance of channels was raised in Slack a few days ago. I am happy to put together a naming scheme convention, as I have already done it before (see [here](https://translate.googleusercontent.com/translate_c?depth=1&hl=fr&ie=UTF8&prev=_t&rurl=translate.google.com&sl=fr&sp=nmt4&tl=en&u=https://github.com/betagouv/beta.gouv.fr/wiki/Slack&xid=17259,15700023,15700105,15700124,15700149,15700168,15700173,15700201&usg=ALkJrhg6tk6bmGjOyMfwnepznDWWw_OT-A#conventions-de-nommage-des-canaux), section “Channel naming conventions”). I received initial support there.

However, finding this issue makes me wonder why the work was not carried on earlier. Is it just because it was full of good intentions but hours were not secured to make it happen, or was another blocker encountered?
Do any of the people who wanted to do it have partial work somewhere? Are they interested in leading this?

**Comment by mdshearer** [comment]
We (Ops) had an initial look over the data, discovered what the most popular channels were and documented them in the comms guideline in the handbook. We haven't got to removing old channels as we haven't been hearing much about the pain it causes and have been focussing on setting up the new subscription model but you should go for it if you want to. We're happy to support in anyway we can!

**Comment by lucasexpresso** [comment]
Matti,

I haven’t been following it. But am happy to support you with context and
bridging you to people active on Slack and Loomio.
Warm wishes
Lucas
