### ISSUE TITLE
review off-boarding process (for overhaul?)

### ISSUE THREAD

**Issue by coopchange** [enspiral/improvements#323]
https://www.loomio.org/d/O0t1xViL/ops-reviewing-the-contributor-opt-out-process

**Comment by charleydavenport** [comment]
As noted in the above Loomio, many of the suggestions, such as adding Slack notifications, getting a primary email address and encouraging contributors to check their details have been implemented.

We've taken on board the suggestions and will extend out the timeframe of Opt-ins to take place over 6-weeks instead of 3 weeks.

We'll also send a list of 10 of these contributors to @susanbasterfield to investigate and will proceed to remove the rest of the non-responses. With ongoing non-responses from now on, we'll simply proceed to offboard after the 6-week mark. Improving Stewarding is an ongoing process which will hopefully cover the existing gaps.
