### ISSUE TITLE
Updating Opt-in Email Workflow to cut through spam filters

### ISSUE THREAD

**Issue by charleydavenport** [enspiral/improvements#339]
Ops team is improving the opt-in messaging to use a different service that can track email opens and has better settings to cut through spam filters as part of ensuring that Contributors are able to receive their messages from Enspiral Foundation... (i just wanted to add an elipsis so this sentence was longer).

**Comment by mdshearer** [comment]
Update: Since Foundation is already using Mailchimp for newsletters we've plugged in to Mailchimp's add-on Mandrill (we've used it before and saves time assessing all the possible tools, it gives foundation 2000 free sends which will keep us going for a while) to send one to one emails.

Now we can setup notifications when someone hasn't read their email for x days or an email soft-bounces which will allow us to be more pro-active when an email isn't getting read.
So far we've moved our opt-in process over, once we've tested that and it's all going fine we'll move over other email processes too.

It also allows us to include all the proper spam protections like SPF and DKIM so our emails aren't getting filtered out of people's inboxes.

**Comment by mdshearer** [comment]
This change also gets us ready for anything that comes out of the new opt-in processes @joshuavial and @agentlewis have been looking at.

**Comment by joshuavial** [comment]
@mdshearer @charleydavenport - is this ticket ready to celebrate?

**Comment by mdshearer** [comment]
Sure. The first phase is complete and working. There's stacks more we would need to do to put all our emails through this new system but we'll call this done.
