### ISSUE TITLE
Are blocks by non-members binding?

### ISSUE THREAD

**Issue by joshuavial** [enspiral/improvements#45]

**Comment by agentlewis** [comment]
hmmm for me this is a symptom of a problem with how we have structured members/contributors. As such I would rather see us put energy there instead of working a fix for the symptom.

eg an ex-member now contributor again or member on hiatus sees a proposal and thinks that it is bad for enspiral should be able to block.

after my recent experience with blocking I think a good interim step would be a guide to blocking that explicitly says you need to have reached out via skype/dm/face2face with the facilitator of the loomio and talk about it. secondly you need to comment that you are not feeling the proposal and are thinking about blocking it. You also need to explain why.

slightly tangental
I have noticed that we have different subjective uses of our proposal system - for me I am quite happy for there to be one or more block on the proposal - the way I have imagined it is that this is a quick list of the core objectors to the proposal whom If I want it to pass I need to engage. This "way" sits counter to the way the enspiral culture currently works so I have had to adopt it. It is also not explicit. eg the handbook does not say that there can only be one block on at a time.  As such we will continue to have people misuse blocks as per how we define them - because our definition is implicitly held by those who have been around long enough.

**Comment by agentlewis** [comment]
is tat refined enough to be scoped? or should i aim to create action items

**Comment by joshuavial** [comment]
@agentlewis I like the idea of a 'how to block' guide in the handbook but see it different to this issue. Have created #153

**Comment by joshuavial** [comment]
This is being dealt with by the members circle tickets
