### ISSUE TITLE
Fix Website Typo

### ISSUE THREAD

**Issue by susanbasterfield** [enspiral/improvements#450]
In the main description on the Venture page, Add the word 'a' before garden

**Comment by danalexilewis** [comment]
Done

**Comment by danalexilewis** [comment]
@coopchange hey bud, quick checkin on how waffle (powered by github)  works. once things are move to Done they are "closed" automatically. Correspondingly moving it out reopens it. This will also send email notifications to everyone involved.

I suggest that with adding the celebrate column  you make it the Catalyst job to clear the celebrate column into done once a month. That way all the issues to be celebrated are collected over a month and can be reported/bubbled up to the network before they are closed by the catalyst. 

this also feels like a nice simple checkpoint where the catalyst maybe can ask "is this actually closed"

**Comment by coopchange** [comment]
yup yup i didn't realize it would re-open it but gathered that post- moving
it...

when you finish stuff, if ya would, pop it into celebrate as every two
weeks (end of sprints) I clear them out -> put em in done as part of my
Catalyst report, and then two weeks later I archive them from done.

I'll give the "is this actually closed" thing a ponder—not wagering too
many people mistakenly close them? I could be wrong... I don't feel like
enough people use waffle to make a lot of maintenance/ people engagement
around it that worthwhile at the moment. I could certainly be convinced
otherwise. Right now I do try to get people on it if they are doing
operational stewardship stuff, but for me i feel like i can navigate it
usefully even with other people using it in their own way or leaving stuff
up (for the moment being)

Could be good to give it a scrub on some (quarterly? twice-a-year?) cadence
though... hmm...
