### ISSUE TITLE
Add List of Members to Handbook

### ISSUE THREAD

**Issue by susanbasterfield** [enspiral/improvements#74]

**Comment by joshuavial** [comment]
Bouncing this back to the backlog

**Comment by mdshearer** [comment]
@susanbasterfield Are you still interested in this?

**Comment by charleydavenport** [comment]
We basically need to make a publicly accessible version of the updated Directory. We could create a new sheet that is open to the public that is simply pulling in selected Data from this directory of Members. https://docs.google.com/spreadsheets/d/1-ZdYOEZ9KXpd8W166Pt-uTQdrsoXcmgZkURU3955L-w/edit#gid=206903456

But would you want the emails accessible? Isn't the list of Members on the website providing this? Could the handbook simply provide a link to that page on the website? Otherwise, we could have a link to the "public" version of the google sheet database. OR perhaps we could create a public Trello board of current Members... ideas ideas.

**Comment by joshuavial** [comment]
@charleydavenport a publicly accessible list sounds good - I think it should be an opt in though. A contributor actively ticks a - yes I want my data publicly visible. We definitely shouldn't publish emails though.

**Comment by phoebetickell** [comment]
@charleydavenport a Trello board of current Members sounds interesting... like the MfC group recently shared. Where did this exploration get to? Could someone explain to me where the data for the Members list on the website comes from, and whether we could link that data to the handbook? Or why a link to the webpage in the handbook wouldn't satisfy this?

**Comment by mdshearer** [comment]
@phoebetickell Exploration is paused but could be taken up anytime if there is enough interest.
As I understand it, Susan get's the information for the website from a Google form I think and adds it manually. A link to the webpage sounds a lot simpler though! I think we're (Susan/Ops) doing a fairly good job of keeping it up-to-date now... *touch wood*

**Comment by coopchange** [comment]
@mdshearer having a Members page in the Handbook that just linked to the website seems like a great quick fix

**Comment by mdshearer** [comment]
I've added a link to the People page. It's an MVP option as the people page only had "To be done" on it. "Someone should" update that! ;)
