### ISSUE TITLE
real time variable contributions

### ISSUE THREAD

**Issue by joshuavial** [enspiral/improvements#79]
Bucket has been raised, ops are 70% of the way through

- [x] build semi-automated system
- [x] trial on some users
- [ ] network wide announcement in the loomio thread
- [x] page in handbook about variable contributions

**Comment by phillcoxon** [comment]
@joshuavial - We are inviting a few users to test now (Susan being the first) and unless anything comes up during that process we are good to announce to the network.  I'd say we should be good to announce to the network as a live product by the end of next week (allowing our test persons to pay and get processed).

**Comment by joshuavial** [comment]
Fantastic - I wonder if we need to have anything in the handbook about the process.

**Comment by phillcoxon** [comment]
@joshuavial - yes, that is something I mentioned in the Catalyst Demo.  A page in the handbook explaining how variable contributions work for both businesses and individuals would be great as it is somewhat confusing.  Contributions from individuals are treated as tax free gifts. Businesses contributions are treated as pre-tax funds and hence the business should keep 28% aside to pay for tax.  

Having a page explaining this in the handbook will be great for both explaining the process and showing that the tax implications were researched and thought out ahead of time.

Additionally I'd suggest we have a URL to the handbook page on every variable contribution invoice so that anyone referring to the invoices at a later date (end of financial year, for example) will have the details they may need at that time.

**Comment by joshuavial** [comment]
Great, I've added another checklist item to the improvement @phillcoxon

**Comment by phillcoxon** [comment]
@joshuavial - a pull request for the handbook info page is waiting for review for inclusion in the handbook: https://github.com/enspiral/handbook/pull/9/files

**Comment by joshuavial** [comment]
Page merged @phillcoxon

**Comment by joshuavial** [comment]
How close is this to going @phillcoxon @mdshearer ?

**Comment by phillcoxon** [comment]
It's good to go!

**Comment by agentlewis** [comment]
nice work peeps :)

**Comment by joshuavial** [comment]
Great, I've dropped a link into the news instead of a new loomio thread.
